permalink: /blog/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "_tempstash", "_revokedposts", "_archivedposts"]
pygments: false

title : mike. hodnick. blog.
tagline: mikes blog
author :
  name : Mike Hodnick
  email : mike.hodnick@gmail.com
  github : kindohm
  twitter : kindohm
  feedburner : Kindohm

production_url : http://blog2.kindohm.com
